# https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Training-Configuration-File.md
# https://github.com/Unity-Technologies/ml-agents/blob/release_3_docs/docs/Training-ML-Agents.md#training-configurations
behaviors:
  Snake:
    max_steps: 1000000000  # Max training steps
    time_horizon: 100  # Max steps before env reset
    summary_freq: 100  # Print summary freq
    keep_checkpoints: 3  # Number of checkpoints to keep
    checkpoint_interval: 1000  # Number of steps before saving better model