# https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Training-Configuration-File.md
trainer_type: ppo
summary_freq: 100  # Every n games, print summary
max_steps: 100  # Number of max moves that the RL agent can make before game ends
keep_checkpoints: 1  # The maximum number of checkpoints to keep
checkpoint_interval: 100  # The number of experiences collected before saving the model checkpoints
